# Generated by Django 3.0.8 on 2020-07-16 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=150, verbose_name='إسم المحامي')),
                ('invoice_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان الفاتورة')),
                ('customer_name', models.CharField(max_length=150, verbose_name='إسم الموكل')),
                ('file_id', models.CharField(max_length=50, verbose_name='رقم الملف')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاريخ اللإصدار')),
            ],
            options={
                'verbose_name': 'الفواتير',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
            options={
                'verbose_name': 'انواع القضايا',
                'verbose_name_plural': 'انواع القضايا',
            },
        ),
        migrations.CreateModel(
            name='InvoicesInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='البند')),
                ('cost', models.FloatField(verbose_name='التكلفة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Invoice')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_title', models.CharField(max_length=250, verbose_name='إسم المكتب')),
                ('office_logo', models.ImageField(blank=True, upload_to='', verbose_name='شعار المكتب')),
                ('taxes_percent', models.FloatField(default=0, help_text='سيتم حساب النسبة المئوية التي ستدخلها من كل فاتورة وإضافتها الي مجموع تكلفة الفاتورة', verbose_name='النسبة المئوية للضرائب')),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعدادات الفواتير',
                'verbose_name_plural': 'إعدادات الفواتير',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.InvoiceTypes', verbose_name='نوع القضية'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
