# Generated by Django 3.0.8 on 2020-07-16 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoicesInputs',
            new_name='InvoiceInputs',
        ),
        migrations.AlterModelOptions(
            name='invoiceinputs',
            options={'verbose_name': 'بند', 'verbose_name_plural': 'بنود الفواتير'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
