# Generated by Django 3.0.8 on 2020-07-18 00:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20200716_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 7, 18, 0, 58, 23, 53310, tzinfo=utc), verbose_name='تاريخ الفاتورة'),
        ),
    ]
