# Generated by Django 3.0.8 on 2020-07-18 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20200718_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 7, 18), verbose_name='تاريخ الفاتورة'),
        ),
    ]
