# Generated by Django 3.0.8 on 2020-07-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20200718_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateField(verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='إسم الموكل'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الملف'),
        ),
        migrations.AlterField(
            model_name='invoiceinputs',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_inputs', to='office.Invoice'),
        ),
    ]
