# Generated by Django 3.0.8 on 2020-07-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0005_auto_20200728_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesetting',
            name='lawyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
