# Generated by Django 3.0.8 on 2020-08-17 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0006_auto_20200728_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('case_id', models.CharField(max_length=100)),
                ('court', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_mobile', models.CharField(blank=True, max_length=15)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_agenda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
