# Generated by Django 3.0.8 on 2020-08-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
