# Generated by Django 3.0.8 on 2020-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_agenda_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='case_year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
