# Generated by Django 3.0.8 on 2020-08-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_remove_agenda_case_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='case_year',
            field=models.CharField(default=2, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
