# Generated by Django 3.0.8 on 2020-08-18 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0011_auto_20200818_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_mobile', models.CharField(blank=True, max_length=15)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_assigned', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
