# Generated by Django 3.0.8 on 2020-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_auto_20200818_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerindex',
            name='file_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
