# Generated by Django 3.0.8 on 2020-08-20 01:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0013_customerindex_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^[0][1][2?0?5?1]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='customerindex',
            name='customer_mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^[0][1][2?0?5?1]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='customerindex',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerindex',
            name='file_id',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='ContractsForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('contract', tinymce.models.HTMLField()),
                ('contract_file', models.FileField(upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(['docm', 'doc', 'dot', 'pdf', 'docx', 'rtf'])])),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
