# Generated by Django 3.0.8 on 2020-09-05 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_auto_20200820_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerindex',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
