# Generated by Django 3.0.8 on 2020-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0016_customerindex_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerindex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
