# Generated by Django 3.0.8 on 2020-09-22 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0017_auto_20200905_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='registered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
