# Generated by Django 3.0.8 on 2020-07-15 18:51

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='الاسم الاول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='default.png', null=True, upload_to=accounts.models.user_folder_direction, validators=[django.core.validators.validate_image_file_extension], verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='المحفظة'),
        ),
    ]
