# Generated by Django 3.0.8 on 2020-07-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200715_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_assistant_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_reset_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assistant_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
