# Generated by Django 3.0.8 on 2020-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='عن المحامي'),
        ),
        migrations.AddField(
            model_name='user',
            name='Specialties',
            field=models.ManyToManyField(blank=True, max_length=500, null=True, to='accounts.Specialties', verbose_name='التخصصات'),
        ),
    ]
