# Generated by Django 3.0.8 on 2020-08-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200805_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_assistant_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_assistant_delete',
            field=models.BooleanField(default=False),
        ),
    ]
