# Generated by Django 3.0.8 on 2020-08-09 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(default='+20', max_length=6, verbose_name='كود الدولة'),
        ),
        migrations.AddField(
            model_name='user',
            name='onsite_cost',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_cost',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='assistant_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
