# Generated by Django 3.0.8 on 2020-08-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200818_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
