# Generated by Django 3.0.8 on 2020-08-23 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_data_is_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف غير صحيح', regex='^[0][1][2?0?5?1]\\d{8}$')]),
        ),
    ]
