# Generated by Django 3.0.8 on 2020-09-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200823_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, max_length=500, related_name='all_specialties', to='accounts.Specialties', verbose_name='التخصصات'),
        ),
    ]
